package moon.backend.data;

import moon.dependency.scripting.MoonEvent;
import haxe.Json;
#if sys
import moonchart.formats.fnf.legacy.*;
import moonchart.formats.fnf.*;
import moonchart.formats.*;
import sys.FileSystem;
import sys.io.File;
#end
import haxe.io.Path;

using StringTools;

/**
 * Structure for the Chart's notes.
 */
typedef NoteStruct =
{
	/**
	 * The note's time in milliseconds.
	 */
	var time:Float;

	/**
	 * The note's direction. It can go from 0 to 3.
	 */
	var data:Int;

	/**
	 * The note's lane. Currently supported are "p1" and "opponent".
	 */
	var lane:String;

	/**
	 * The note's type.
	 */
	var type:String;

	/**
	 * The note's hold duration.
	 */
	var duration:Float;

	/**
	 * The note's values. Used for triggering specific actions when hit.
	 */
	var ?values:Dynamic;
};

/**
 * Structure for the Chart's events.
**/
typedef EventStruct =
{
	/**
	 * The event's tag.
	 */
	var tag:String;

	/**
	 * The event's values.
	 */
	var values:Dynamic;

	/**
	 * The event's time in miliseconds.
	 */
	var time:Float;

	/**
	 * The event's lane, used for the chart editor.
	 */
	var ?lane:Int;

	/**
	 * If true, this event will be executed a single time, immediately once
	 * PlayState finishes loading.
	 */
	var ?runOnLoad:Bool;
};

/**
 * Struct for a bookmark.
 * Only visible in the chart editor.
**/
typedef BookmarkStruct =
{
	/**
	 * The text that'll be displayed in it.
	 */
	var text:String;

	/**
	 * The person who wrote it.
	 */
	var ?author:String;

	/**
	 * The time in milisseconds.
	 */
	var time:Float;
};

/**
 * Structure for the Chart's metadata.
**/
typedef MetadataStruct =
{
	// -- Game data

	/**
	 * The song's BPM. It can have decimal numbers.
	 */
	var bpm:Float;

	/**
	 * The song's time signature. Default is [4, 4] (which is the same as 4/4)
	 */
	var timeSignature:Array<Int>;

	/**
	 * The song's scroll speed.
	 * Do note that it feels a bit more faster in Moon Engine rather than V-Slice, for example.
	 */
	var scrollSpd:Float;

	/**
	 * The stage in which will be used for the song.
	 */
	var stage:String;

	/**
	 * The available lanes. Default is `["opponent", "p1"]`.
	 */
	var lanes:Array<String>;

	/**
	 * All the characters that'll be at the "players" group on the stage.
	 */
	var players:Array<String>;

	/**
	 * All the characters that'll be at the "spectators" group on the stage.
	 */
	var spectators:Array<String>;

	/**
	 * All the characters that'll be at the "opponents" group on the stage.
	 */
	var opponents:Array<String>;

	/**
	 * The noteskin in which the game will use. Defaults to v-slice.
	 */
	var ?noteskin:String;

	/**
	 * Whether or not should the song do a countdown on the beginning.
	 */
	var ?hasCountdown:Bool;

	// -- Other data

	/**
	 * The song name that'll be displayed in menus.
	 */
	var displayName:String;

	/**
	 * The album in which this song belongs to.
	 */
	var album:String;

	/**
	 * The artist in which made the song.
	 */
	var artist:String;

	/**
	 * The charter in which charted the song.
	 */
	var charter:String;

	/**
	 * The song preview. First value is where it starts, and last value is where it ends.
	 */
	var preview:Array<Float>;

	// -- MISC

	/**
	 * Shows if this chart was generated by the game, or converted using moon-chart.
	 */
	var generatedBy:String;

	/**
	 * The version of the game this chart was made in.
	 */
	var version:String;

	// -- Difficulty-specific extras

	/**
	 * Multiplier for health gain/loss. Defaults to 1.0.
	 */
	var ?healthMultiplier:Float;

	/**
	 * Manual override for the auto-calculated difficulty rating (0-20).
	 * If null, the rating is calculated automatically.
	 */
	var ?difficultyRating:Int;
};

/**
 * Structure for the entire Chart.
**/
typedef ChartStruct =
{
	/**
	 * The chart's metadata.
	 * Can be null if metadata is stored in a separate file.
	 */
	var ?meta:MetadataStruct;

	/**
	 * The chart's notes.
	 */
	var notes:Array<NoteStruct>;

	/**
	 * The chart's bookmarks, only displayed in the chart editor.
	 */
	var ?bookmarks:Array<BookmarkStruct>;
};

typedef MultiChartFile =
{
	var notes:Dynamic;
	var ?bookmarks:Dynamic;
};

/**
 * Class used for handling ingame charts.
**/
class Chart
{
	/**
	 * All the chart formats supported for converting.
	 */
	public static final SUPPORTED_FORMATS:Array<String> = [
		'legacy',
		'psych',
		'codename',
		'v-slice',
		'osu',
		'kade',
		'fps-plus'
	];

	/**
	 * Fields that are commonly difficulty-specific and should be stored as maps.
	 */
	public static final DIFF_SPECIFIC_META_FIELDS:Array<String> = [
		'scrollSpd',
		'healthMultiplier',
		'difficultyRating',
		'noteskin',
		'hasCountdown'
	];

	/**
	 * All of the chart content, except for the events.
	 */
	public var content:ChartStruct;

	/**
	 * All of the chart's events.
	 */
	public var events:Array<EventStruct>;

	/**
	 * The song's name. (not displayName!)
	 */
	public var song:String;

	/**
	 * The song's difficulty.
	 */
	public var difficulty:String;

	/**
	 * The song's mix.
	 */
	public var mix:String;

	/**
	 * Loads a chart from a path.
	 *
	 * @param song        The song's name. (e.g. satin panties)
	 * @param difficulty  The song's difficulty. (e.g. hard)
	 * @param mix         The song's mix. (e.g. bf)
	 */
	public function new(song:String, difficulty:String = 'hard', mix:String = 'bf')
	{
		this.song = song;
		this.difficulty = difficulty;
		this.mix = mix;

		final suffix = getDifficultySuffix(difficulty);
		events = loadEventsWithSuffix(song, mix, suffix);
		content = loadChartContent(song, mix, difficulty, suffix);
		content.meta = loadMetadata(song, mix, suffix, difficulty, content.meta);
		content.meta.hasCountdown ??= true;
		content.meta.healthMultiplier ??= 1.0;

		if (content.notes == null || content.notes.length == 0) return;

		var seen = new Map<String, Bool>();
		var unique:Array<NoteStruct> = [];
		var duplicatesFound:Int = 0;

		for (note in content.notes)
		{
			final key = '${note.time}_${note.data}_${note.lane}';
			if (!seen.exists(key))
			{
				seen.set(key, true);
				unique.push(note);
			}
			else
				duplicatesFound++;
		}

		content.notes = unique;
		if (duplicatesFound > 0) trace('Removed $duplicatesFound duplicate note(s) from chart $song/$mix/$difficulty', "DEBUG");
	}

	private function loadChartContent(song:String, mix:String, difficulty:String, suffix:String):ChartStruct
	{
		if (suffix == '')
		{
			final shared:Dynamic = Paths.JSON('songs/$song/$mix/chart');
			if (shared != null)
			{
				final notes = extractDifficultyArray(shared.notes, difficulty);
				if (notes != null)
				{
					return {
						notes: cast notes,
						bookmarks: cast extractDifficultyArray(shared.bookmarks, difficulty),
						meta: shared.meta
					};
				}
			}
		}

		final single:Dynamic = Paths.JSON('songs/$song/$mix/chart-$difficulty');
		if (single != null)
		{
			// Support both legacy flat notes array and keyed multi format inside chart-X.json
			// NOTE: i'm doing this because at time of writing there's some mods that use moon engine
			// and I don't wanna re-convert everything...
			final notes = extractDifficultyArray(single.notes, difficulty);
			return {
				notes: cast(notes ?? (Std.isOfType(single.notes, Array) ? cast single.notes : [])),
				bookmarks: cast(extractDifficultyArray(
					single.bookmarks,
					difficulty
				) ?? (Std.isOfType(single.bookmarks, Array) ? cast single.bookmarks : null)),
				meta: single.meta
			};
		}

		trace('[CHART] Chart file not found for $song/$mix/$difficulty', "WARNING");
		return {
			notes: []
		};
	}

	/**
	 * Pulls an array for a difficulty from either a plain array or a difficulty-keyed object.
	 */
	private static function extractDifficultyArray(value:Dynamic, difficulty:String):Null<Array<Dynamic>>
	{
		if (value == null) return null;
		if (Std.isOfType(value, Array)) return cast value;
		if (Type.typeof(value) == TObject && Reflect.hasField(value, difficulty))
		{
			final field = Reflect.field(value, difficulty);
			if (Std.isOfType(field, Array)) return cast field;
		}
		return null;
	}

	/**
	 * Loads events for a song, trying the suffix-specific file first.
	 */
	private function loadEventsWithSuffix(song:String, mix:String, suffix:String):Array<EventStruct>
	{
		if (suffix != '' && Paths.exists('songs/$song/$mix/events$suffix.json')) return cast Paths.JSON('songs/$song/$mix/events$suffix') ?? [];

		if (Paths.exists('songs/$song/$mix/events.json')) return cast Paths.JSON('songs/$song/$mix/events') ?? [];

		return [];
	}

	/**
	 * Loads and resolves metadata for a song.
	 */
	private function loadMetadata(song:String, mix:String, suffix:String, difficulty:String, embeddedMeta:MetadataStruct):MetadataStruct
	{
		var meta:Dynamic = embeddedMeta;

		if (Paths.exists('songs/$song/$mix/meta.json')) meta = mergeMetadata(meta, Paths.JSON('songs/$song/$mix/meta'));

		if (suffix != '' && Paths.exists('songs/$song/$mix/meta$suffix.json')) meta = mergeMetadata(meta, Paths.JSON('songs/$song/$mix/meta$suffix'));

		if (meta == null)
		{
			trace('[CHART] WARNING: No metadata found for $song/$mix/$difficulty, using defaults!', "WARNING");
			meta = getDefaultMetadata();
		}

		return resolveMetadata(meta, difficulty);
	}

	/**
	 * Resolves a metadata structure, expanding any per-difficulty map values
	 * to their concrete values for the given difficulty.
	 */
	private function resolveMetadata(meta:Dynamic, difficulty:String):MetadataStruct
	{
		final resolved:MetadataStruct = {
			bpm: resolveVal(meta.bpm, difficulty, 120.0),
			timeSignature: resolveVal(meta.timeSignature, difficulty, [4, 4]),
			scrollSpd: resolveVal(meta.scrollSpd, difficulty, 2.0),
			stage: resolveVal(meta.stage, difficulty, 'stage'),
			lanes: resolveVal(meta.lanes, difficulty, ["opponent", "p1"]),
			players: resolveVal(meta.players, difficulty, ["bf"]),
			spectators: resolveVal(meta.spectators, difficulty, ["gf"]),
			opponents: resolveVal(meta.opponents, difficulty, ["dad"]),
			noteskin: resolveVal(meta.noteskin, difficulty, 'v-slice'),
			hasCountdown: resolveVal(meta.hasCountdown, difficulty, true),
			displayName: resolveVal(meta.displayName, difficulty, song),
			album: resolveVal(meta.album, difficulty, ''),
			artist: resolveVal(meta.artist, difficulty, ''),
			charter: resolveVal(meta.charter, difficulty, ''),
			preview: cast resolveVal(meta.preview, difficulty, [0, 0]),
			generatedBy: resolveVal(meta.generatedBy, difficulty, 'Moon Engine'),
			version: resolveVal(meta.version, difficulty, '1.0.0'),
		};

		resolved.healthMultiplier = resolveVal(meta.healthMultiplier, difficulty, 1.0);
		resolved.difficultyRating = resolveVal(meta.difficultyRating, difficulty, -1);

		return resolved;
	}

	/**
	 * Resolves a single value that might be a per-difficulty map.
	 */
	private static function resolveVal<T>(value:Dynamic, difficulty:String, defaultValue:T):T
	{
		if (value == null) return defaultValue;

		if (Type.typeof(value) == TObject)
		{
			if (Reflect.hasField(value, difficulty))
			{
				final v = Reflect.field(value, difficulty);
				if (v != null) return v;
			}

			if (Reflect.hasField(value, 'default'))
			{
				final v = Reflect.field(value, 'default');
				if (v != null) return v;
			}

			return defaultValue;
		}

		return value;
	}

	/**
	 * Deep-merges two metadata objects. Fields in `overrider` take priority.
	 * Nested anonymous objects are merged recursively! Everything else is replaced.
	 */
	private static function mergeMetadata(base:Dynamic, overrider:Dynamic):Dynamic
	{
		if (base == null) return overrider;
		if (overrider == null) return base;

		final result:Dynamic = Reflect.copy(base);

		for (field in Reflect.fields(overrider))
		{
			final overrideVal = Reflect.field(overrider, field);
			final baseVal = Reflect.field(base, field);

			if (Type.typeof(overrideVal) == TObject && Type.typeof(baseVal) == TObject) Reflect.setField(result, field, mergeMetadata(baseVal, overrideVal));
			else
				Reflect.setField(result, field, overrideVal);
		}

		return result;
	}

	/**
	 * Returns a default MetadataStruct with sensible fallback values.
	 */
	private function getDefaultMetadata():MetadataStruct
	{
		return {
			bpm: 120.0,
			timeSignature: [4, 4],
			scrollSpd: 2.0,
			stage: 'stage',
			lanes: ["opponent", "p1"],
			players: ["bf"],
			spectators: ["gf"],
			opponents: ["dad"],
			noteskin: 'v-slice',
			hasCountdown: true,
			displayName: song,
			album: '',
			artist: '',
			charter: '',
			preview: [0, 0],
			generatedBy: 'Moon Engine',
			version: Constants.INDEV_VERSION,
			healthMultiplier: 1.0,
		};
	}

	/**
	 * Gets the file suffix for a given difficulty.
	 * @param difficulty The difficulty name (e.g. "erect")
	 * @return The suffix string (e.g. "-erect") or empty string
	 */
	public static function getDifficultySuffix(difficulty:String):String
	{
		final diff = SongLibrary.getDifficulty(difficulty);
		return diff?.suffix ?? '';
	}

	/**
	 * Whether this difficulty uses the shared multi-diff chart/meta files (no suffix).
	 */
	public static function isSharedDifficulty(difficulty:String):Bool return getDifficultySuffix(difficulty) == '';

	/**
	 * Relative path for the chart file of a difficulty.
	 */
	public static function chartPath(song:String, mix:String, difficulty:String):String
	{
		if (isSharedDifficulty(difficulty)) return 'songs/$song/$mix/chart';
		return 'songs/$song/$mix/chart-$difficulty';
	}

	/**
	 * Relative path for events of a difficulty.
	 */
	public static function eventsPath(song:String, mix:String, difficulty:String):String
	{
		final suffix = getDifficultySuffix(difficulty);
		return suffix != '' ? 'songs/$song/$mix/events$suffix' : 'songs/$song/$mix/events';
	}

	/**
	 * Relative path for metadata of a difficulty.
	 */
	public static function metaPath(song:String, mix:String, difficulty:String):String
	{
		final suffix = getDifficultySuffix(difficulty);
		return suffix != '' ? 'songs/$song/$mix/meta$suffix' : 'songs/$song/$mix/meta';
	}

	/**
	 * Returns the difficulty rating for this chart.
	 */
	public function getDifficultyRating():Int
	{
		if (content.meta.difficultyRating != null && content.meta.difficultyRating >= 0) return content.meta.difficultyRating;
		return calculateDifficultyRating(content.notes, content.meta.bpm);
	}

	/**
	 * Calculates a clean 0-20 difficulty rating based on NPS, chords, and jacks.
	 * @param notes The array containing all notes.
	 * @param bpm   The BPM value.
	 */
	public static function calculateDifficultyRating(notes:Array<NoteStruct>, bpm:Float):Int
	{
		if (notes == null || notes.length == 0) return 0;

		var p1Notes:Array<NoteStruct> = [];
		for (note in notes) if (note.lane == "p1") p1Notes.push(note);

		if (p1Notes.length == 0) return 0;

		p1Notes.sort((a, b) -> a.time < b.time ? -1 : a.time > b.time ? 1 : 0);

		final songDuration:Float = p1Notes[p1Notes.length - 1].time - p1Notes[0].time;
		if (songDuration <= 0) return 0;

		final WINDOW_MS:Float = 1000.0;
		var npsValues:Array<Float> = [];
		var windowStart:Int = 0;

		for (i in 0...p1Notes.length)
		{
			while (p1Notes[i].time - p1Notes[windowStart].time > WINDOW_MS)
				windowStart++;
			npsValues.push((i - windowStart + 1) * (1000.0 / WINDOW_MS));
		}

		npsValues.sort((a, b) -> a < b ? -1 : a > b ? 1 : 0);

		final peakNPS:Float = npsValues[npsValues.length - 1];
		final p90NPS:Float = npsValues[Std.int(npsValues.length * 0.90)];
		var avgNPS:Float = 0.0;
		for (v in npsValues) avgNPS += v;
		avgNPS /= npsValues.length;

		final blendedNPS:Float = (peakNPS * 0.45) + (p90NPS * 0.45) + (avgNPS * 0.10);

		var chordNotes:Int = 0;
		for (i in 1...p1Notes.length) if (Math.abs(p1Notes[i].time - p1Notes[i - 1].time) < 15.0) chordNotes++;

		final chordFactor:Float = 1.0 + (chordNotes / p1Notes.length) * 0.25;

		var jackNotes:Int = 0;
		for (i in 1...p1Notes.length)
		{
			final gap:Float = p1Notes[i].time - p1Notes[i - 1].time;
			if (p1Notes[i].data == p1Notes[i - 1].data && gap > 15.0 && gap < 250.0) jackNotes++;
		}

		final jackFactor:Float = 1.0 + (jackNotes / p1Notes.length) * 0.15;
		final bpmFactor:Float = 1.0 + Math.max(0.0, (bpm - 120.0) / 120.0) * 0.20;
		final adjustedNPS:Float = blendedNPS * chordFactor * jackFactor * bpmFactor;
		final normalized:Float = Math.pow(adjustedNPS / 16.0, 2.0);
		final e2x:Float = Math.exp(2.0 * normalized);

		return Std.int(Math.min(20, Math.max(0, Math.round(20.0 * (e2x - 1.0) / (e2x + 1.0)))));
	}

	/**
	 * Returns all notes of a specific type.
	 */
	public static function getNotesByType(notes:Array<NoteStruct>, type:String):Array<NoteStruct> return notes.filter(n -> n.type == type);

	/**
	 * Returns all notes on a specific lane.
	 */
	public static function getNotesByLane(notes:Array<NoteStruct>, lane:String):Array<NoteStruct> return notes.filter(n -> n.lane == lane);

	/**
	 * Changes an array of notes to a specific type.
	 */
	public static function changeNoteType(notes:Array<NoteStruct>, oldType:String, newType:String):Void for (n in notes) if (n.type == oldType)
		n.type = newType;

	/**
	 * Changes an array of notes to a specific lane.
	 */
	public static function changeNoteLane(notes:Array<NoteStruct>, fromLane:String, toLane:String):Void for (n in notes) if (n.lane == fromLane)
		n.lane = toLane;

	public static function findCompanionFile(chartPath:String, suffix:String):Null<String>
	{
		#if !sys return null; #end

		final dir = Path.directory(chartPath);
		final name = Path.withoutExtension(Path.withoutDirectory(chartPath));

		final candidates = [
			'$dir/$name$suffix',
			'$dir/$name-$suffix',
			'$dir/$suffix',
			'$dir/events$suffix',
			'$dir/meta$suffix'
		];

		for (c in candidates)
		{
			final jsonPath = c.endsWith(".json") ? c : '$c.json';
			if (Paths.exists(jsonPath)) return jsonPath;
		}

		if (FileSystem.exists(dir) && FileSystem.isDirectory(dir))
		{
			for (f in FileSystem.readDirectory(dir)) if (f.toLowerCase().contains(suffix.toLowerCase()) && f.endsWith(".json")) return Path.join([dir, f]);
		}

		return null;
	}

	/**
	 * Saves this chart's notes, events, and metadata back to their respective files.
	 *
	 * @param saveBookmarks Whether to persist bookmarks into the chart file. Defaults to true.
	 */
	public function save(saveBookmarks:Bool = true):Void
	{
		#if sys
		final suffix = getDifficultySuffix(difficulty);
		final chartKey = chartPath(song, mix, difficulty) + '.json';
		final baseRoot = Mods.getOwningModRoot(chartKey) ?? Paths.getVanillaPath('');

		if (suffix == '') saveSharedChart(baseRoot, saveBookmarks);
		else
			saveSingleChart(baseRoot, saveBookmarks);

		Paths.saveFileContentTo(baseRoot, eventsPath(song, mix, difficulty) + '.json', Json.stringify(events, "\t"));

		if (suffix == '') saveSharedMeta(baseRoot);
		else
			Paths.saveFileContentTo(baseRoot, metaPath(song, mix, difficulty) + '.json', Json.stringify(content.meta, "\t"));

		trace('[CHART] Saved chart $song/$mix/$difficulty', "DEBUG");
		#else
		throw 'Saving charts is not available in this platform!';
		#end
	}

	#if sys
	private function saveSharedChart(baseRoot:String, saveBookmarks:Bool):Void
	{
		final path = 'songs/$song/$mix/chart.json';
		var file:Dynamic = {};

		if (Paths.exists(path))
		{
			final existing = Paths.JSON('songs/$song/$mix/chart');
			if (existing != null) file = existing;
		}

		// Promote legacy flat array into a difficulty map if needed.
		if (file.notes == null) file.notes = {};
		else if (Std.isOfType(file.notes, Array))
		{
			final legacy:Array<Dynamic> = cast file.notes;
			file.notes = {};
			Reflect.setField(file.notes, difficulty, legacy);
		}

		Reflect.setField(file.notes, difficulty, content.notes);

		if (saveBookmarks && content.bookmarks != null)
		{
			if (file.bookmarks == null) file.bookmarks = {};
			else if (Std.isOfType(file.bookmarks, Array))
			{
				final legacyBm:Array<Dynamic> = cast file.bookmarks;
				file.bookmarks = {};
				Reflect.setField(file.bookmarks, difficulty, legacyBm);
			}
			Reflect.setField(file.bookmarks, difficulty, content.bookmarks);
		}

		Paths.saveFileContentTo(baseRoot, path, Json.stringify(file, "\t"));
	}

	private function saveSingleChart(baseRoot:String, saveBookmarks:Bool):Void
	{
		final chartToSave:Dynamic = {
			notes: content.notes
		};
		if (saveBookmarks && content.bookmarks != null) chartToSave.bookmarks = content.bookmarks;

		Paths.saveFileContentTo(baseRoot, 'songs/$song/$mix/chart-$difficulty.json', Json.stringify(chartToSave, "\t"));
	}

	private function saveSharedMeta(baseRoot:String):Void
	{
		final path = 'songs/$song/$mix/meta.json';
		var file:Dynamic = {};

		if (Paths.exists(path))
		{
			final existing = Paths.JSON('songs/$song/$mix/meta');
			if (existing != null) file = existing;
		}

		// Shared fields
		// BRO THIS FORMATTERRRR
		final sharedFields = [
			        'bpm', 'timeSignature',  'stage',   'lanes', 'players',  'spectators', 'opponents',
			'displayName',         'album', 'artist', 'charter', 'preview', 'generatedBy',   'version'
		];
		for (field in sharedFields) Reflect.setField(file, field, Reflect.field(content.meta, field));

		// difficulty-specific fields stored as maps keyed by difficulty name.
		for (field in DIFF_SPECIFIC_META_FIELDS)
		{
			final value = Reflect.field(content.meta, field);
			if (value == null) continue;

			var map:Dynamic = Reflect.field(file, field);
			if (map == null || Type.typeof(map) != TObject || Std.isOfType(map, Array)) map = {};

			Reflect.setField(map, difficulty, value);
			Reflect.setField(file, field, map);
		}

		Paths.saveFileContentTo(baseRoot, path, Json.stringify(file, "\t"));
	}
	#end

	private static function writeJson(path:String, data:Dynamic):Void Paths.saveFileContent(path + '.json', Json.stringify(data, "\t"));

	/**
	 * Converts a chart type to Moon Engine's format for a single difficulty.
	 */
	public static function convert(type:String, path:String, difficulty:String, ?metaPath:String, applyNoteRules:Bool = true):ConvertResult
	{
		final batch = convertMany(type, path, [difficulty], metaPath, applyNoteRules);
		if (batch == null || batch.results.length == 0) return null;
		return batch.results[0];
	}

	/**
	 * Converts one or more difficulties from a source chart into Moon Engine format.
	 *
	 * @param type           Source format id (see SUPPORTED_FORMATS)
	 * @param path           Path to the source chart file
	 * @param difficulties   Difficulties to convert (must exist in the source, or erect←nightmare)
	 * @param metaPath       Optional companion meta path for formats that need it
	 * @param applyNoteRules Whether to remap note kinds via NOTE_TYPE_RULES
	 * @param rawScrollMap   Optional pre-parsed scrollSpeed map from the raw chart JSON
	 */
	public static function convertMany(type:String, path:String, difficulties:Array<String>, ?metaPath:String, applyNoteRules:Bool = true, ?rawScrollMap:Dynamic):ConvertBatch
	{
		#if sys
		if (difficulties == null || difficulties.length == 0) throw 'convertMany requires at least one difficulty';

		final loadDiff = difficulties[0] == 'erect' ? 'nightmare' : difficulties[0];
		final vslice = loadAsVSlice(type, path, metaPath, loadDiff).stringify();
		final data:Dynamic = Json.parse(vslice.data);
		final metadata:Dynamic = Json.parse(vslice.meta);

		// Prefer the full per-difficulty scroll map.
		if (rawScrollMap != null) data.scrollSpeed = rawScrollMap;
		else if (path != null && FileSystem.exists(path))
		{
			try
			{
				final raw:Dynamic = Json.parse(File.getContent(path));
				if (
					raw != null
					&& raw.scrollSpeed != null
					&& Type.typeof(raw.scrollSpeed) == TObject
					&& !Std.isOfType(raw.scrollSpeed, Array)
				) data.scrollSpeed = raw.scrollSpeed;
			}
			catch (_)
			{
			}
		}

		final results:Array<ConvertResult> = [];
		final sharedNotes:Dynamic = {};
		final sharedMetaMaps:Map<String, Dynamic> = new Map();
		var sharedEvents:Array<EventStruct> = null;
		var baseMeta:MetadataStruct = null;

		for (diff in difficulties)
		{
			final notes = convertNotesForDifficulty(data, diff, applyNoteRules);
			final events = convertEvents(data, metadata);
			final meta = convertMetadata(data, metadata, diff);

			results.push({
				difficulty: diff,
				chartJson: Json.stringify({
					notes: notes
				}, "\t"),
				eventsJson: Json.stringify(events, "\t"),
				metaJson: Json.stringify(meta, "\t"),
				notes: notes,
				events: events,
				meta: meta
			});

			if (isSharedDifficulty(diff))
			{
				Reflect.setField(sharedNotes, diff, notes);
				if (sharedEvents == null) sharedEvents = events;
				if (baseMeta == null) baseMeta = meta;

				for (field in DIFF_SPECIFIC_META_FIELDS)
				{
					if (!sharedMetaMaps.exists(field)) sharedMetaMaps.set(field, {
					});
					Reflect.setField(sharedMetaMaps.get(field), diff, Reflect.field(meta, field));
				}
			}
		}

		var sharedChartJson:String = null;
		var sharedEventsJson:String = null;
		var sharedMetaJson:String = null;

		if (baseMeta != null)
		{
			sharedChartJson = Json.stringify({
				notes: sharedNotes
			}, "\t");
			sharedEventsJson = Json.stringify(sharedEvents ?? [], "\t");

			final metaOut:Dynamic = Reflect.copy(baseMeta);
			for (field => map in sharedMetaMaps) Reflect.setField(metaOut, field, map);
			sharedMetaJson = Json.stringify(metaOut, "\t");
		}

		return {
			results: results,
			sharedChartJson: sharedChartJson,
			sharedEventsJson: sharedEventsJson,
			sharedMetaJson: sharedMetaJson
		};
		#else
		throw 'Chart conversion is currently only available for Desktop.';
		return null;
		#end
	}

	/**
	 * Converts an entire song folder and returns one batch per mix.
	 */
	public static function convertFolder(type:String, folderPath:String, difficulties:Array<String>, applyNoteRules:Bool = true):Array<FolderConvertResult>
	{
		#if sys
		if (!FileSystem.exists(folderPath) || !FileSystem.isDirectory(folderPath)) throw 'Folder not found: $folderPath';

		return switch (type)
		{
			case 'v-slice':
				convertVSliceFolder(folderPath, difficulties, applyNoteRules);
			case 'codename':
				convertCodenameFolder(folderPath, difficulties, applyNoteRules);
			default:
				throw 'Folder conversion is only set up for v-slice and codename (got $type). Sorry brah!';
		};
		#else
		throw 'Chart conversion is currently only available for Desktop.';
		return null;
		#end
	}

	#if sys
	private static function convertVSliceFolder(folder:String, difficulties:Array<String>, applyNoteRules:Bool):Array<FolderConvertResult>
	{
		final files = FileSystem.readDirectory(folder);
		final chartFiles:Array<String> = [];
		for (f in files) if (f.endsWith('.json') && f.contains('-chart')) chartFiles.push(f);

		if (chartFiles.length == 0) throw 'No V-Slice *-chart*.json files found in $folder';

		// song id text before "-chart"
		final songId = chartFiles[0].substring(0, chartFiles[0].indexOf('-chart'));
		final out:Array<FolderConvertResult> = [];

		for (chartFile in chartFiles)
		{
			// self notes dont mind me..
			// Patterns: id-chart.json | id-chart-erect.json | id-chart-pico.json | id-chart-pico-erect.json
			var rest = chartFile.substring(songId.length + '-chart'.length);
			if (rest.endsWith('.json')) rest = rest.substr(0, rest.length - 5);

			var mix = 'bf';
			var variation = ''; // "" or "erect"
			if (rest == '' || rest == '-erect')
			{
				mix = 'bf';
				variation = rest == '-erect' ? 'erect' : '';
			}
			else
			{
				// -pico or -pico-erect whatever
				final parts = rest.substr(1).split('-'); // drop leading '-' lol
				if (parts.length >= 1 && parts[parts.length - 1] == 'erect')
				{
					variation = 'erect';
					parts.pop();
				}
				mix = parts.join('-');
				if (mix == '') mix = 'bf';
			}

			final chartPath = Path.join([folder, chartFile]);
			final metaName = variation == '' ? '$songId-metadata.json' : (mix == 'bf' ? '$songId-metadata-erect.json' : '$songId-metadata-$mix${variation != "" ? "-" + variation : ""}.json');
			var metaPath = Path.join([folder, metaName]);
			if (!FileSystem.exists(metaPath))
			{
				final alt = [
					Path.join([folder, '$songId-metadata-$mix.json']),
					Path.join([folder, '$songId-metadata.json']),
					Path.join([
						folder,
						variation == 'erect' ? '$songId-metadata-erect.json' : '$songId-metadata.json'
					])
				];
				metaPath = null;
				for (a in alt) if (FileSystem.exists(a))
				{
					metaPath = a;
					break;
				}
			}

			final diffsForFile = difficulties.filter(d ->
			{
				if (variation == 'erect') return d == 'erect';
				return d != 'erect' && isSharedDifficulty(d);
			});
			if (diffsForFile.length == 0) continue;

			final batch = convertMany('v-slice', chartPath, diffsForFile, metaPath, applyNoteRules);
			out.push({
				song: songId,
				mix: mix,
				batch: batch,
				sourceChart: chartPath
			});
		}

		final merged:Map<String, FolderConvertResult> = new Map();
		for (entry in out)
		{
			final key = entry.mix;
			if (!merged.exists(key))
			{
				merged.set(key, entry);
				continue;
			}

			final existing = merged.get(key);
			for (r in entry.batch.results) existing.batch.results.push(r);

			if (entry.batch.sharedChartJson != null && existing.batch.sharedChartJson == null)
			{
				existing.batch.sharedChartJson = entry.batch.sharedChartJson;
				existing.batch.sharedEventsJson = entry.batch.sharedEventsJson;
				existing.batch.sharedMetaJson = entry.batch.sharedMetaJson;
			}
		}

		return[for (v in merged) v];
	}

	private static function convertCodenameFolder(folder:String, difficulties:Array<String>, applyNoteRules:Bool):Array<FolderConvertResult>
	{
		final chartsDir = Path.join([folder, 'charts']);
		if (!FileSystem.exists(chartsDir) || !FileSystem.isDirectory(chartsDir)) throw 'Codename folder needs a charts/ directory: $folder';

		var metaPath:String = null;
		for (name in ['meta.json', 'data.json', 'Meta.json'])
		{
			final p = Path.join([folder, name]);
			if (FileSystem.exists(p))
			{
				metaPath = p;
				break;
			}
		}

		final songId = Path.withoutDirectory(folder);
		final results:Array<ConvertResult> = [];
		final sharedNotes:Dynamic = {};
		final sharedMetaMaps:Map<String, Dynamic> = new Map();
		var sharedEvents:Array<EventStruct> = null;
		var baseMeta:MetadataStruct = null;

		for (diff in difficulties)
		{
			final chartFile = Path.join([chartsDir, '$diff.json']);
			if (!FileSystem.exists(chartFile)) continue;

			final one = convertMany('codename', chartFile, [diff], metaPath, applyNoteRules);
			if (one == null || one.results.length == 0) continue;

			final r = one.results[0];
			results.push(r);

			if (isSharedDifficulty(diff))
			{
				Reflect.setField(sharedNotes, diff, r.notes);
				if (sharedEvents == null) sharedEvents = r.events;
				if (baseMeta == null) baseMeta = r.meta;
				for (field in DIFF_SPECIFIC_META_FIELDS)
				{
					if (!sharedMetaMaps.exists(field)) sharedMetaMaps.set(field, {
					});
					Reflect.setField(sharedMetaMaps.get(field), diff, Reflect.field(r.meta, field));
				}
			}
		}

		if (results.length == 0) throw 'No Codename chart files matched the selected difficulties in $chartsDir';

		var sharedChartJson:String = null;
		var sharedEventsJson:String = null;
		var sharedMetaJson:String = null;
		if (baseMeta != null)
		{
			sharedChartJson = Json.stringify({
				notes: sharedNotes
			}, "\t");
			sharedEventsJson = Json.stringify(sharedEvents ?? [], "\t");
			final metaOut:Dynamic = Reflect.copy(baseMeta);
			for (field => map in sharedMetaMaps) Reflect.setField(metaOut, field, map);
			sharedMetaJson = Json.stringify(metaOut, "\t");
		}

		return [{
			song: songId,
			mix: 'bf',
			batch: {
				results: results,
				sharedChartJson: sharedChartJson,
				sharedEventsJson: sharedEventsJson,
				sharedMetaJson: sharedMetaJson
			},
			sourceChart: chartsDir
		}];
	}
	#end

	public static function writeConvertBatch(batch:ConvertBatch, song:String, mix:String, ?root:String):Void
	{
		#if sys
		final baseRoot = root ?? Paths.getVanillaPath('');
		final dir = 'songs/$song/$mix';

		if (batch.sharedChartJson != null)
		{
			Paths.saveFileContentTo(baseRoot, '$dir/chart.json', batch.sharedChartJson);
			if (batch.sharedEventsJson != null) Paths.saveFileContentTo(baseRoot, '$dir/events.json', batch.sharedEventsJson);
			if (batch.sharedMetaJson != null) Paths.saveFileContentTo(baseRoot, '$dir/meta.json', batch.sharedMetaJson);
		}

		for (result in batch.results)
		{
			if (isSharedDifficulty(result.difficulty)) continue;

			final suffix = getDifficultySuffix(result.difficulty);
			Paths.saveFileContentTo(baseRoot, '$dir/chart-${result.difficulty}.json', result.chartJson);
			Paths.saveFileContentTo(baseRoot, '$dir/events$suffix.json', result.eventsJson);
			if (result.metaJson != null) Paths.saveFileContentTo(baseRoot, '$dir/meta$suffix.json', result.metaJson);
		}
		#else
		throw 'Chart conversion is currently only available for Desktop.';
		#end
	}

	#if sys
	private static function loadAsVSlice(type:String, path:String, metaPath:Null<String>, difficulty:String):Dynamic
	{
		return switch (type)
		{
			case 'psych':
				new FNFVSlice().fromFormat(new FNFPsych().fromFile(path, null, difficulty));
			case 'codename':
				new FNFVSlice().fromFormat(new FNFCodename().fromFile(path, metaPath, difficulty));
			case 'legacy':
				new FNFVSlice().fromFormat(new FNFLegacy().fromFile(path, null, difficulty));
			case 'osu':
				new FNFVSlice().fromFormat(new OsuMania().fromFile(path, null, difficulty));
			case 'fps-plus':
				new FNFVSlice().fromFormat(new FNFFpsPlus().fromFile(path, null, difficulty));
			case 'kade':
				new FNFVSlice().fromFormat(new FNFKade().fromFile(path, null, difficulty));
			default:
				new FNFVSlice().fromFile(path, metaPath, difficulty);
		};
	}

	/**
	 * Maps source difficulty keys when consolidating charts.
	 */
	private static function resolveSourceDifficulty(notesObj:Dynamic, difficulty:String):String
	{
		if (notesObj == null) return difficulty;
		if (Reflect.hasField(notesObj, difficulty)) return difficulty;
		if (difficulty == 'erect' && Reflect.hasField(notesObj, 'nightmare')) return 'nightmare';
		return difficulty;
	}

	// TODO: take a deeper look onto all kinds?

	/**
	 * Note-type remap rules applied during conversion.
	 */
	public static final NOTE_TYPE_RULES:Map<String, String> = [
		'Alt Animation' => 'Alt Animation Note',
		'No Animation' => 'No Animation Note',
		'No Anim' => 'No Animation Note',
		'GF Sing' => 'GF Sing',
		'Girlfriend Sing' => 'GF Sing',
		'Hurt Note' => 'Hurt Note',
		'Instakill Note' => 'Instakill Note',
		'Phantom Note' => 'Phantom Note'
	];

	private static function applyNoteTypeRule(kind:Null<String>):Null<String>
	{
		if (kind == null || kind == '') return null;
		if (NOTE_TYPE_RULES.exists(kind)) return NOTE_TYPE_RULES.get(kind);
		return kind;
	}

	private static function convertNotesForDifficulty(data:Dynamic, difficulty:String, applyRules:Bool = true):Array<NoteStruct>
	{
		final out:Array<NoteStruct> = [];
		var noteArray:Array<Dynamic> = null;

		if (data.notes != null)
		{
			if (Std.isOfType(data.notes, Array)) noteArray = cast data.notes;
			else
			{
				final sourceDiff = resolveSourceDifficulty(data.notes, difficulty);
				if (Reflect.hasField(data.notes, sourceDiff)) noteArray = Reflect.field(data.notes, sourceDiff);
			}
		}

		if (noteArray == null) return out;

		for (note in noteArray)
		{
			final rawKind:Null<String> = (note.k == null || note.k == '') ? null : note.k;
			out.push({
				time: note.t,
				data: (note.d > 3) ? Std.int(note.d - 4) : note.d,
				lane: (note.d > 3) ? 'opponent' : 'p1',
				type: applyRules ? applyNoteTypeRule(rawKind) : rawKind,
				duration: note.l ?? 0.0,
				values: {
				}
			});
		}

		out.sort((a, b) -> a.time < b.time ? -1 : a.time > b.time ? 1 : 0);
		return out;
	}

	private static function convertEvents(data:Dynamic, metadata:Dynamic):Array<EventStruct>
	{
		final converted:Array<EventStruct> = [];
		final events:Array<Dynamic> = data.events ?? [];

		for (event in events) converted.push(mapEvent(event));

		final tChanges:Array<Dynamic> = metadata.timeChanges ?? [];
		for (i in 1...tChanges.length)
		{
			converted.push({
				tag: 'Change Playback Settings',
				values: {
					bpm: tChanges[i].bpm,
					timeSignature: [tChanges[i]?.n ?? 4, tChanges[i]?.d ?? 4]
				},
				time: tChanges[i].t
			});
		}

		converted.sort((a, b) -> a.time < b.time ? -1 : a.time > b.time ? 1 : 0);
		return converted;
	}

	private static function mapEvent(event:Dynamic):EventStruct
	{
		return switch (event.e)
		{
			case 'FocusCamera':
				{
					tag: 'Move Camera',
					values: {
						character: (event?.v?.char == 1 ?? 0) ? 'opponent' : (event?.v?.char == 2 ?? 0) ? 'spectator' : (event?.v?.char == -1 ?? 0) ? 'none' : 'player',
						duration: (event.v.ease == 'CLASSIC') ? 26 : event?.v?.duration ?? 26,
						ease: (event.v.ease == 'CLASSIC') ? 'expoOut' : '${event?.v?.ease ?? "expo"}${event?.v?.easeDir ?? ""}',
						x: Std.parseFloat('${event?.v?.x ?? "0"}') ?? 0,
						y: Std.parseFloat('${event?.v?.y ?? "0"}') ?? 0,
					},
					lane: 0,
					time: event.t
				};

			case 'ZoomCamera':
				{
					tag: 'Set Zoom',
					values: {
						zoom: Std.parseFloat(event.v.zoom),
						duration: event?.v?.duration ?? 8,
						ease: '${event?.v?.ease ?? "expo"}${event?.v?.easeDir ?? "Out"}' ?? 'circOut',
						mode: event?.v?.mode ?? 'absolute',
					},
					lane: 1,
					time: event.t
				};

			case 'SetCameraBop':
				{
					tag: 'Customized Pulse Timing',
					values: event.v,
					lane: 2,
					time: event.t
				};

			case 'PlayAnimation':
				{
					tag: 'Play Character Animation',
					time: event.t,
					lane: 3,
					values: {
						anim: event.v.anim,
						target: (event.v.target == 'dad') ? 'opponent' : (event.v.target == 'boyfriend') ? 'player' : 'spectator',
						force: event?.v?.force ?? true,
						forceOverride: true,
						reversed: false,
						frame: 0
					}
				};

			case 'ScrollSpeed':
				{
					tag: 'Set Lane Scroll Speed',
					time: event.t,
					lane: 1,
					values: {
						duration: event.v.duration,
						strumline: event.v.strumline,
						ease: '${event?.v?.ease ?? "expo"}${event?.v?.easeDir ?? ""}' ?? 'circOut',
						scroll: event.v.scroll,
						absolute: event.v.absolute
					}
				};

			default:
				{
					tag: event.e,
					values: event.v,
					time: event.t,
					lane: 0
				};
		};
	}

	private static function convertMetadata(data:Dynamic, metadata:Dynamic, difficulty:String):MetadataStruct
	{
		final t0 = (metadata.timeChanges != null && metadata.timeChanges.length > 0) ? metadata.timeChanges[0] : null;
		final playData = metadata.playData;
		final chars = playData.characters;

		// Prefer nightmare scroll values when converting erect (V-Slice consolidation).
		var scrollDiff = difficulty;
		if (
			difficulty == 'erect'
			&& data.scrollSpeed != null
			&& Type.typeof(data.scrollSpeed) == TObject
			&& !Std.isOfType(data.scrollSpeed, Array)
			&& Reflect.hasField(data.scrollSpeed, 'nightmare')
			&& !Reflect.hasField(data.scrollSpeed, 'erect')
		) scrollDiff = 'nightmare';

		return {
			bpm: t0?.bpm ?? 120.0,
			timeSignature: [t0?.n ?? 4, t0?.d ?? 4],
			scrollSpd: (data.scrollSpeed != null) ? resolveVal(data.scrollSpeed, scrollDiff, 2.0) : 2.0,
			stage: playData.stage ?? 'stage',
			lanes: ["opponent", "p1"],
			players: [chars.player ?? 'bf'],
			spectators: [chars.girlfriend ?? 'gf'],
			opponents: [chars.opponent ?? 'dad'],
			noteskin: 'v-slice',
			hasCountdown: true,
			displayName: metadata.songName ?? '',
			album: playData.album ?? '',
			artist: metadata.artist ?? '',
			charter: metadata.charter ?? '',
			preview: [playData.previewStart ?? 0, playData.previewEnd ?? 150000],
			generatedBy: metadata.generatedBy ?? 'Moon Engine Converter',
			version: metadata.version ?? '1.0.0',
			healthMultiplier: 1.0
		};
	}
	#end
}

@:dox(hide)
typedef ConvertResult =
{
	/**
	 * Difficulty this result belongs to.
	 */
	var ?difficulty:String;

	/**
	 * The chart JSON.
	 */
	var chartJson:String;

	/**
	 * The events JSON.
	 */
	var eventsJson:String;

	/**
	 * The metadata JSON.
	 */
	var ?metaJson:String;

	/**
	 * Parsed notes.
	 */
	var ?notes:Array<NoteStruct>;

	/**
	 * Parsed events.
	 */
	var ?events:Array<EventStruct>;

	/**
	 * Parsed metadata.
	 */
	var ?meta:MetadataStruct;
};

/**
 * Result of converting several difficulties at once.
 */
@:dox(hide)
typedef ConvertBatch =
{
	var results:Array<ConvertResult>;
	var ?sharedChartJson:String;
	var ?sharedEventsJson:String;
	var ?sharedMetaJson:String;
};

/**
 * One mix produced by folder conversion.
 */
@:dox(hide)
typedef FolderConvertResult =
{
	var song:String;
	var mix:String;
	var batch:ConvertBatch;
	var ?sourceChart:String;
};
